In [1]:
import torch
from torch.nn import MSELoss

In [3]:
out = torch.Tensor([[0.1, 0.2, 0.5, 0.3], [0.3, 0.5, 0.1, 0.01]])
out

tensor([[0.1000, 0.2000, 0.5000, 0.3000],
        [0.3000, 0.5000, 0.1000, 0.0100]])

tensor([[0.1000, 0.2000, 0.5000, 0.3000],
        [0.3000, 0.5000, 0.1000, 0.0100]])

In [4]:
b = torch.Tensor([1, 3])
b

tensor([1., 3.])

In [8]:
out.gather(1, b.type(torch.int64).unsqueeze(1)).squeeze(1)

tensor([0.2000, 0.0100])

In [11]:
out.max(1)[0]

tensor([0.5000, 0.5000])

In [9]:
gas = -1

In [10]:
[]


[0.0, 1]

In [20]:
import torch
# first = torch.rand(2).unsqueeze(1)
# second = torch.rand(1000).unsqueeze(1)
# third = torch.rand(10).unsqueeze(1)
# third

tensor([[0.6883],
        [0.0823],
        [0.2069],
        [0.1683],
        [0.2234],
        [0.9440],
        [0.6035],
        [0.1681],
        [0.9624],
        [0.5928]])

In [55]:
a = torch.rand(3,2)
x = torch.rand(3,2)

In [68]:
ones_vector = torch.ones(3)
ones_vector.shape

torch.Size([3])

In [71]:
dones = torch.IntTensor([True, False, False])
dones.shape

torch.Size([3])

In [73]:
b = ones_vector-dones
b.shape

torch.Size([3])

In [75]:
print(a.shape)
print(b.unsqueeze(1).shape)
c = a*b.unsqueeze(1)
c

torch.Size([3, 2])
torch.Size([3, 1])


tensor([[0.0000, 0.0000],
        [0.3987, 0.7470],
        [0.6365, 0.4506]])

In [62]:
d=c+b.unsqueeze(1)
d

tensor([[0.0000, 0.0000],
        [1.3987, 1.7470],
        [1.6365, 1.4506]])

In [64]:
torch.nn.MSELoss()(x, d)

tensor(1.1240)

In [63]:
x

tensor([[0.4632, 0.9523],
        [0.4636, 0.3119],
        [0.2460, 0.5814]])

In [ ]:
0 - 1.4155 = 1.4155 = 2.003
3.1457 - 0.7755 = 2.3702
3.0871 - 0.8274 = 2.2597